config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    article = Article.create(article_params)
    redirect_to article_path(article.id)
  end

  def show() end

  def edit() end

  def update
    @article.update(article_params)
    redirect_to article_path(@article.id)
  end

  def destroy
    Article.destroy(params['id'])
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end

  def set_article
    @article = Article.find(params['id'])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<div id="edit">
  <h1>Edit Article</h1>

  <%= render "components/form", article: @article %>

  <ul id="links">
    <%= link_to article_path(@article.id) do %>
      <i class="fa-solid fa-rotate-left smaller"></i>
      Back to article
    <% end %>
  </ul>
</div>

app/views/articles/index.html.erb
<div id="index">
  <% @articles.each do |a| %>
    <div class="index-article">
      <%= link_to a.title, article_path(a.id) %>
      <p><%= a.content %></p>
    </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<div id="new">
  <h1>New Article</h1>

  <%= render "components/form", article: @article %>
</div>

app/views/articles/show.html.erb
<div id="show">
  <div class="show-title">
    <h1><%= @article.title %></h1>

    <%= link_to edit_article_path(@article.id) do%>
      <i class="fa-solid fa-pencil"></i>
    <% end %>

    <%= link_to article_path(@article.id), data: { turbo_method: :delete } do%>
      <i class="fa-solid fa-trash-can"></i>
    <% end %>
  </div>
  <p><%= @article.content %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# Font Awesome %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "components/header" %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>